import path from "node:path";
import {
	TRACK_CLOSEOUT_END_MARKER,
	TRACK_CLOSEOUT_START_MARKER,
	TRACK_CONTEXT_MESSAGE_TYPE,
	TRACK_STATUS_KEY,
	TRACK_SUMMARY_VERSION,
	TRACK_TRACE_ENTRY_TYPE,
} from "./constants.js";
import {
	clear_active_track,
	get_active_track,
	list_tracks_sync,
	read_track_file,
	read_track_metadata,
	read_track_record,
	regenerate_missing_track_files,
	update_track_metadata,
	write_track_file,
} from "./storage.js";
import type { TrackContextMessageDetails, TrackMetadata, TrackRecord, TrackTraceEntry } from "./types.js";
import { track_trace_entry_schema } from "./types.js";

export function mark_session_active(track_record: TrackRecord, session_track: string | undefined): TrackRecord {
	return {
		...track_record,
		is_active: track_record.slug === session_track,
	};
}

function collect_markdown_list_items(
	markdown: string,
	limit: number,
	options?: { checkboxes_only?: boolean },
): string[] {
	const items: string[] = [];

	for (const raw_line of markdown.split(/\r?\n/)) {
		const line = raw_line.trim();
		if (!line || line.startsWith("#") || line.startsWith(">") || line.startsWith("```") || line.startsWith("<!--")) {
			continue;
		}

		const checkbox_match = line.match(/^[-*]\s+\[(.| )\]\s+(.+)$/);
		if (checkbox_match) {
			const state = checkbox_match[1]?.trim().toLowerCase();
			if (options?.checkboxes_only && state && state !== "") {
				continue;
			}
			items.push(`- ${checkbox_match[2].trim()}`);
			if (items.length >= limit) break;
			continue;
		}

		if (options?.checkboxes_only) {
			continue;
		}

		const bullet_match = line.match(/^[-*]\s+(.+)$/) ?? line.match(/^\d+\.\s+(.+)$/);
		if (bullet_match) {
			items.push(`- ${bullet_match[1].trim()}`);
			if (items.length >= limit) break;
		}
	}

	return items;
}

function collect_report_pulse(markdown: string): string[] {
	const lines = markdown.split(/\r?\n/);
	const paragraph: string[] = [];

	for (const raw_line of lines) {
		const line = raw_line.trim();
		if (!line || line.startsWith("#") || line.startsWith("-") || line.startsWith("*") || /^\d+\./.test(line)) {
			if (paragraph.length > 0) break;
			continue;
		}
		if (line.startsWith("<!--") || line.startsWith("```")) {
			continue;
		}
		paragraph.push(line);
		if (paragraph.join(" ").length >= 280) break;
	}

	if (paragraph.length > 0) {
		return [paragraph.join(" ")];
	}

	return collect_markdown_list_items(markdown, 3);
}

function render_section(title: string, lines: string[], fallback: string): string {
	const body = lines.length > 0 ? lines.join("\n") : `- ${fallback}`;
	return `## ${title}\n${body}`;
}

export function build_track_summary_markdown(input: {
	slug: string;
	metadata: TrackMetadata;
	tasks_md: string;
	findings_md: string;
	decisions_md: string;
	report_md: string;
}): string {
	const next_steps = collect_markdown_list_items(input.tasks_md, 6);
	const open_checklist = collect_markdown_list_items(input.tasks_md, 6, { checkboxes_only: true });
	const findings = collect_markdown_list_items(input.findings_md, 4);
	const decisions = collect_markdown_list_items(input.decisions_md, 4);
	const report_pulse = collect_report_pulse(input.report_md);
	const related_paths =
		input.metadata.related_paths.length > 0
			? input.metadata.related_paths.map((item) => `- ${item}`)
			: ["- none recorded"];
	const session_count = typeof input.metadata.session_count === "number" ? input.metadata.session_count : 0;

	return [
		"# Track summary",
		"",
		"> Deterministic snapshot generated by /track sync. Update the source files in this track, then resync.",
		"",
		"## Snapshot",
		`- Track: ${input.slug}`,
		`- Purpose: ${input.metadata.purpose}`,
		`- Status: ${input.metadata.status}`,
		`- Last synced: ${input.metadata.last_synced_at}`,
		`- Session count: ${session_count}`,
		`- Summary version: ${input.metadata.summary_version ?? TRACK_SUMMARY_VERSION}`,
		"",
		"## Related paths",
		...related_paths,
		"",
		render_section("Next steps", next_steps, "No next steps captured yet."),
		"",
		render_section("Open checklist", open_checklist, "No open checklist items captured yet."),
		"",
		render_section("Findings", findings, "No durable findings captured yet."),
		"",
		render_section("Decisions", decisions, "No decisions captured yet."),
		"",
		render_section("Report pulse", report_pulse, "No report update captured yet."),
		"",
	].join("\n");
}

async function write_track_summary(track_record: TrackRecord, metadata: TrackMetadata): Promise<void> {
	const [tasks_md, findings_md, decisions_md, report_md] = await Promise.all([
		read_track_file(track_record.dir, "tasks.md"),
		read_track_file(track_record.dir, "findings.md"),
		read_track_file(track_record.dir, "decisions.md"),
		read_track_file(track_record.dir, "report.md"),
	]);

	const summary = build_track_summary_markdown({
		slug: track_record.slug,
		metadata,
		tasks_md,
		findings_md,
		decisions_md,
		report_md,
	});
	await write_track_file(track_record.dir, "summary.md", summary);
}

export async function sync_track_record(tracks_dir: string, name_or_slug: string): Promise<TrackRecord> {
	const track_record = await read_track_record(tracks_dir, name_or_slug);
	await regenerate_missing_track_files(track_record.dir, track_record.metadata);

	const now = new Date().toISOString();
	const metadata = await update_track_metadata(track_record.dir, (current) => ({
		...current,
		updated_at: now,
		last_synced_at: now,
		summary_version: TRACK_SUMMARY_VERSION,
	}));

	const synced_record: TrackRecord = {
		...track_record,
		metadata,
		missing_files: [],
	};
	await write_track_summary(synced_record, metadata);
	return {
		...synced_record,
		metadata: await read_track_metadata(track_record.dir),
	};
}

function build_closeout_block(closed_at: string): string {
	return [
		TRACK_CLOSEOUT_START_MARKER,
		"## Closeout",
		`- Closed at: ${closed_at}`,
		"- This track is closed.",
		"- Follow-up automation outside .pi/tracks/ is intentionally out of scope for this extension.",
		TRACK_CLOSEOUT_END_MARKER,
		"",
	].join("\n");
}

function finalize_report_markdown(report_md: string, closed_at: string): string {
	const closeout_block = build_closeout_block(closed_at);
	const start_index = report_md.indexOf(TRACK_CLOSEOUT_START_MARKER);
	const end_index = report_md.indexOf(TRACK_CLOSEOUT_END_MARKER);

	if (start_index !== -1 && end_index !== -1 && end_index > start_index) {
		const before = report_md.slice(0, start_index).replace(/\s+$/, "");
		const after = report_md.slice(end_index + TRACK_CLOSEOUT_END_MARKER.length).replace(/^\s+/, "");
		return `${before}\n\n${closeout_block}${after ? `${after}\n` : ""}`;
	}

	const trimmed = report_md.replace(/\s+$/, "");
	return `${trimmed}\n\n${closeout_block}`;
}

export async function end_track_record(tracks_dir: string, name_or_slug: string): Promise<TrackRecord> {
	const synced = await sync_track_record(tracks_dir, name_or_slug);
	const closed_at = new Date().toISOString();
	const report_md = await read_track_file(synced.dir, "report.md");
	await write_track_file(synced.dir, "report.md", finalize_report_markdown(report_md, closed_at));

	const metadata = await update_track_metadata(synced.dir, (current) => ({
		...current,
		status: "closed",
		closed_at,
		updated_at: closed_at,
		last_synced_at: closed_at,
		summary_version: TRACK_SUMMARY_VERSION,
	}));

	const ended_record: TrackRecord = {
		...synced,
		metadata,
	};
	await write_track_summary(ended_record, metadata);
	return ended_record;
}

export function serialize_track_for_agent(track_record: TrackRecord): string {
	const lines = [
		`Track: ${track_record.slug}`,
		`Purpose: ${track_record.metadata.purpose}`,
		`Status: ${track_record.metadata.status}`,
		`Active: ${track_record.is_active ? "yes" : "no"}`,
		`Last synced: ${track_record.metadata.last_synced_at}`,
		`Missing files: ${track_record.missing_files.length > 0 ? track_record.missing_files.join(", ") : "none"}`,
	];

	if (track_record.metadata.related_paths.length > 0) {
		lines.push("Related paths:");
		for (const related_path of track_record.metadata.related_paths) {
			lines.push(`- ${related_path}`);
		}
	}

	return lines.join("\n");
}

export function serialize_track_list_for_agent(track_records: TrackRecord[]): string {
	if (track_records.length === 0) {
		return "No tracks found.";
	}

	return track_records
		.map((track_record) => {
			const active_marker = track_record.is_active ? "*" : "-";
			const missing =
				track_record.missing_files.length > 0 ? ` · missing: ${track_record.missing_files.join(", ")}` : "";
			return `${active_marker} ${track_record.slug} · ${track_record.metadata.status} · ${track_record.metadata.purpose}${missing}`;
		})
		.join("\n");
}

export function build_track_argument_completions(
	prefix: string,
	track_records: TrackRecord[],
	tokenize: (value: string) => string[],
): Array<{ value: string; label: string; description?: string }> | null {
	const tokens = tokenize(prefix);
	const sub_commands = ["new", "use", "list", "status", "sync", "end"];

	if (tokens.length <= 1 && !prefix.endsWith(" ")) {
		const query = tokens[0] ?? "";
		const matches = sub_commands.filter((sub_command) => sub_command.startsWith(query));
		return matches.length > 0 ? matches.map((sub_command) => ({ value: sub_command, label: sub_command })) : null;
	}

	const sub_command = tokens[0] ?? "";
	if (!["use", "status", "sync", "end"].includes(sub_command)) {
		return null;
	}

	const track_query = prefix.endsWith(" ") ? "" : (tokens[tokens.length - 1] ?? "");
	const matches = track_records.filter((track_record) => track_record.slug.startsWith(track_query));
	if (matches.length === 0) {
		return null;
	}

	return matches.map((track_record) => ({
		value: `${sub_command} ${track_record.slug}`,
		label: track_record.slug,
		description: `${track_record.metadata.status} · ${track_record.metadata.purpose}`,
	}));
}

export function build_track_context_injection(
	track_record: TrackRecord,
	agents_md: string,
	summary_md: string,
): string {
	return [
		"",
		"# Active Track",
		"",
		`The current session is attached to the track '${track_record.slug}'. Use the track-local map and summary below before reading deeper files.`,
		"",
		`<track name="${track_record.slug}" status="${track_record.metadata.status}">`,
		"## Track AGENTS.md",
		agents_md.trim(),
		"",
		"## Track summary.md",
		summary_md.trim(),
		"</track>",
		"",
		"Do not assume anything outside this track unless the repository code or docs confirm it.",
	].join("\n");
}

export function build_track_context_message(track_record: TrackRecord): {
	customType: string;
	content: string;
	display: true;
	details: TrackContextMessageDetails;
} {
	return {
		customType: TRACK_CONTEXT_MESSAGE_TYPE,
		content: `Loaded track context: ${track_record.slug}`,
		display: true,
		details: {
			track: track_record.slug,
			purpose: track_record.metadata.purpose,
			status: track_record.metadata.status,
		},
	};
}

export function build_track_trace_entry(
	action: TrackTraceEntry["action"],
	track?: string,
	status?: TrackTraceEntry["status"],
): TrackTraceEntry {
	return {
		action,
		track,
		status,
		timestamp: new Date().toISOString(),
	};
}

export function get_latest_track_trace(
	branch: Array<{ type: string; customType?: string; data?: unknown }>,
): TrackTraceEntry | undefined {
	for (let index = branch.length - 1; index >= 0; index -= 1) {
		const entry = branch[index];
		if (entry.type !== "custom" || entry.customType !== TRACK_TRACE_ENTRY_TYPE) {
			continue;
		}
		const parsed = track_trace_entry_schema.safeParse(entry.data);
		if (parsed.success) {
			return parsed.data;
		}
	}
	return undefined;
}

export function get_session_track_slug(
	branch: Array<{ type: string; customType?: string; data?: unknown }>,
): string | undefined {
	const latest_trace = get_latest_track_trace(branch);
	if (latest_trace?.action !== "set-active") {
		return undefined;
	}
	return latest_trace.track;
}

export async function restore_track_status(ctx: {
	cwd: string;
	sessionManager: { getBranch: () => Array<{ type: string; customType?: string; data?: unknown }> };
	ui: { setStatus: (key: string, value: string | undefined) => void; notify: (message: string, level: string) => void };
}): Promise<void> {
	const tracks_dir = path.resolve(ctx.cwd, ".pi/tracks");
	const active_track = get_session_track_slug(ctx.sessionManager.getBranch());

	if (!active_track) {
		ctx.ui.setStatus(TRACK_STATUS_KEY, undefined);
		return;
	}

	const track_record = read_track_record_sync_safe(tracks_dir, active_track);
	if (!track_record) {
		ctx.ui.setStatus(TRACK_STATUS_KEY, `🧵 missing:${active_track}`);
		ctx.ui.notify(
			`Active track '${active_track}' is missing or malformed. Run /track list or /track use <name> to repair the binding.`,
			"warning",
		);
		return;
	}

	ctx.ui.setStatus(TRACK_STATUS_KEY, `🧵 ${active_track}`);
}

function read_track_record_sync_safe(tracks_dir: string, slug: string): TrackRecord | null {
	for (const track_record of list_tracks_sync(tracks_dir)) {
		if (track_record.slug === slug) {
			return track_record;
		}
	}
	return null;
}

export async function clear_active_track_if_matches(tracks_dir: string, slug: string): Promise<boolean> {
	const active_track = await get_active_track(tracks_dir);
	if (active_track !== slug) {
		return false;
	}
	await clear_active_track(tracks_dir);
	return true;
}
