import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { action_create, action_end, action_get, action_list, action_set_active, action_sync } from "../actions.js";
import { create_track_workspace, get_tracks_dir, read_track_file, set_active_track } from "../storage.js";

const temp_dirs: string[] = [];

async function create_temp_cwd(): Promise<string> {
	const cwd = await fs.mkdtemp(path.join(os.tmpdir(), "tracks-actions-"));
	temp_dirs.push(cwd);
	return cwd;
}

async function setup_track(cwd: string, name: string, purpose = "test") {
	const tracks_dir = get_tracks_dir(cwd);
	return create_track_workspace({ tracks_dir, name, purpose });
}

afterEach(async () => {
	await Promise.all(temp_dirs.splice(0).map((dir) => fs.rm(dir, { recursive: true, force: true })));
});

describe("action_list", () => {
	it("lists all tracks with session-active marking", async () => {
		const cwd = await create_temp_cwd();
		const tracks_dir = get_tracks_dir(cwd);
		await setup_track(cwd, "alpha", "first");
		await setup_track(cwd, "beta", "second");

		const result = await action_list(tracks_dir, "beta");
		expect(result.error).toBeUndefined();
		expect(result.tracks).toHaveLength(2);
		expect(result.tracks![0].slug).toBe("alpha");
		expect(result.tracks![0].is_active).toBe(false);
		expect(result.tracks![1].slug).toBe("beta");
		expect(result.tracks![1].is_active).toBe(true);
		expect(result.traces).toEqual([]);
	});

	it("returns empty list when no tracks exist", async () => {
		const cwd = await create_temp_cwd();
		const tracks_dir = get_tracks_dir(cwd);
		const result = await action_list(tracks_dir, undefined);
		expect(result.tracks).toEqual([]);
	});
});

describe("action_get", () => {
	it("gets a track by name", async () => {
		const cwd = await create_temp_cwd();
		const tracks_dir = get_tracks_dir(cwd);
		await setup_track(cwd, "target", "get test");

		const result = await action_get(tracks_dir, undefined, "target");
		expect(result.error).toBeUndefined();
		expect(result.track!.slug).toBe("target");
		expect(result.track!.metadata.purpose).toBe("get test");
		expect(result.traces).toEqual([]);
	});

	it("falls back to session track when no name given", async () => {
		const cwd = await create_temp_cwd();
		const tracks_dir = get_tracks_dir(cwd);
		await setup_track(cwd, "session-track", "fallback test");

		const result = await action_get(tracks_dir, "session-track");
		expect(result.track!.slug).toBe("session-track");
		expect(result.track!.is_active).toBe(true);
	});

	it("returns error when no name and no session track", async () => {
		const cwd = await create_temp_cwd();
		const tracks_dir = get_tracks_dir(cwd);

		const result = await action_get(tracks_dir, undefined);
		expect(result.error).toContain("No track is attached");
		expect(result.track).toBeUndefined();
	});

	it("throws when track does not exist", async () => {
		const cwd = await create_temp_cwd();
		const tracks_dir = get_tracks_dir(cwd);

		await expect(action_get(tracks_dir, undefined, "ghost")).rejects.toThrow("not found");
	});
});

describe("action_create", () => {
	it("creates a track workspace and syncs it", async () => {
		const cwd = await create_temp_cwd();
		const tracks_dir = get_tracks_dir(cwd);

		const result = await action_create(tracks_dir, undefined, {
			name: "new-track",
			purpose: "test creation",
		});
		expect(result.error).toBeUndefined();
		expect(result.track!.slug).toBe("new-track");
		expect(result.track!.metadata.purpose).toBe("test creation");
		expect(result.track!.is_active).toBe(false);
		expect(result.traces).toEqual([]);

		// Verify summary was generated by sync
		const summary = await read_track_file(result.track!.dir, "summary.md");
		expect(summary).toContain("test creation");
	});

	it("creates and activates in one call", async () => {
		const cwd = await create_temp_cwd();
		const tracks_dir = get_tracks_dir(cwd);

		const result = await action_create(tracks_dir, undefined, {
			name: "activated",
			purpose: "test activate",
			activate: true,
		});
		expect(result.error).toBeUndefined();
		expect(result.track!.is_active).toBe(true);
		expect(result.track!.metadata.session_count).toBe(1);
		expect(result.traces).toEqual([{ action: "set-active", track: "activated" }]);
	});

	it("passes related_paths through to workspace creation", async () => {
		const cwd = await create_temp_cwd();
		const tracks_dir = get_tracks_dir(cwd);

		const result = await action_create(tracks_dir, undefined, {
			name: "with-paths",
			purpose: "test paths",
			related_paths: ["src/index.ts", "docs/readme.md"],
		});
		expect(result.track!.metadata.related_paths).toEqual(["src/index.ts", "docs/readme.md"]);
	});

	it("returns error for empty name", async () => {
		const cwd = await create_temp_cwd();
		const tracks_dir = get_tracks_dir(cwd);

		const result = await action_create(tracks_dir, undefined, { name: "", purpose: "test" });
		expect(result.error).toContain("name");
	});

	it("returns error for empty purpose", async () => {
		const cwd = await create_temp_cwd();
		const tracks_dir = get_tracks_dir(cwd);

		const result = await action_create(tracks_dir, undefined, { name: "valid", purpose: "  " });
		expect(result.error).toContain("purpose");
	});

	it("throws when track already exists", async () => {
		const cwd = await create_temp_cwd();
		const tracks_dir = get_tracks_dir(cwd);
		await setup_track(cwd, "dupe");

		await expect(action_create(tracks_dir, undefined, { name: "dupe", purpose: "duplicate" })).rejects.toThrow(
			"already exists",
		);
	});
});

describe("action_set_active", () => {
	it("sets a track as active", async () => {
		const cwd = await create_temp_cwd();
		const tracks_dir = get_tracks_dir(cwd);
		await setup_track(cwd, "target", "activate test");

		const result = await action_set_active(tracks_dir, "target");
		expect(result.error).toBeUndefined();
		expect(result.track!.slug).toBe("target");
		expect(result.track!.is_active).toBe(true);
		expect(result.track!.metadata.session_count).toBe(1);
		expect(result.traces).toEqual([{ action: "set-active", track: "target" }]);
	});

	it("returns error for closed track", async () => {
		const cwd = await create_temp_cwd();
		const tracks_dir = get_tracks_dir(cwd);
		const track = await setup_track(cwd, "closed-one", "test");

		// Close the track by rewriting status in metadata file
		await fs.writeFile(
			path.join(track.dir, "track.yaml"),
			(await fs.readFile(path.join(track.dir, "track.yaml"), "utf8")).replace("status: active", "status: closed"),
			"utf8",
		);

		const result = await action_set_active(tracks_dir, "closed-one");
		expect(result.error).toContain("closed");
		expect(result.traces).toEqual([]);
	});

	it("returns error for empty name", async () => {
		const cwd = await create_temp_cwd();
		const tracks_dir = get_tracks_dir(cwd);

		const result = await action_set_active(tracks_dir, "  ");
		expect(result.error).toContain("name");
	});

	it("throws when track does not exist", async () => {
		const cwd = await create_temp_cwd();
		const tracks_dir = get_tracks_dir(cwd);

		await expect(action_set_active(tracks_dir, "ghost")).rejects.toThrow("not found");
	});
});

describe("action_sync", () => {
	it("syncs a track by name", async () => {
		const cwd = await create_temp_cwd();
		const tracks_dir = get_tracks_dir(cwd);
		const track = await setup_track(cwd, "sync-target", "sync test");

		await fs.writeFile(path.join(track.dir, "tasks.md"), "# Tasks\n\n- New task\n", "utf8");
		const result = await action_sync(tracks_dir, undefined, "sync-target");

		expect(result.error).toBeUndefined();
		expect(result.track!.slug).toBe("sync-target");
		expect(result.traces).toEqual([]);

		const summary = await read_track_file(result.track!.dir, "summary.md");
		expect(summary).toContain("New task");
	});

	it("falls back to session track", async () => {
		const cwd = await create_temp_cwd();
		const tracks_dir = get_tracks_dir(cwd);
		await setup_track(cwd, "session-sync", "fallback");

		const result = await action_sync(tracks_dir, "session-sync");
		expect(result.track!.slug).toBe("session-sync");
	});

	it("returns error when no name and no session track", async () => {
		const cwd = await create_temp_cwd();
		const tracks_dir = get_tracks_dir(cwd);

		const result = await action_sync(tracks_dir, undefined);
		expect(result.error).toContain("No track is attached");
	});
});

describe("action_end", () => {
	it("ends a track, emitting end then clear-active traces", async () => {
		const cwd = await create_temp_cwd();
		const tracks_dir = get_tracks_dir(cwd);
		await setup_track(cwd, "ending", "end test");
		await set_active_track(tracks_dir, "ending");

		const result = await action_end(tracks_dir, "ending", "ending");
		expect(result.error).toBeUndefined();
		expect(result.track!.metadata.status).toBe("closed");
		expect(result.track!.metadata.closed_at).toBeTruthy();

		// Trace ordering: end first, then clear-active
		expect(result.traces).toEqual([
			{ action: "end", track: "ending" },
			{ action: "clear-active", track: "ending" },
		]);

		// Report should have closeout block
		const report = await read_track_file(result.track!.dir, "report.md");
		expect(report).toContain("## Closeout");
	});

	it("skips clear-active trace when track is not the active one", async () => {
		const cwd = await create_temp_cwd();
		const tracks_dir = get_tracks_dir(cwd);
		await setup_track(cwd, "not-active", "end test");
		// Don't set it active

		const result = await action_end(tracks_dir, undefined, "not-active");
		expect(result.traces).toEqual([{ action: "end", track: "not-active" }]);
	});

	it("falls back to session track", async () => {
		const cwd = await create_temp_cwd();
		const tracks_dir = get_tracks_dir(cwd);
		await setup_track(cwd, "session-end", "fallback");

		const result = await action_end(tracks_dir, "session-end");
		expect(result.track!.slug).toBe("session-end");
		expect(result.track!.metadata.status).toBe("closed");
	});

	it("returns error when no name and no session track", async () => {
		const cwd = await create_temp_cwd();
		const tracks_dir = get_tracks_dir(cwd);

		const result = await action_end(tracks_dir, undefined);
		expect(result.error).toContain("No track is attached");
	});
});
